name: Spellcheck Markdown
run-name: ${{ github.actor }} - ${{ github.ref_name }}
on:
   pull_request:
      paths:
      - '/markdown/*.md'
   push:
      paths:
      - '/markdown/*.md'
   workflow_dispatch:
jobs:
    markdown-spelling:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@v4
           with:
            ref: ${{ github.head_Ref }}
         - name: Spell Check
           uses: UnicornGlobal/spellcheck-github-actions@master
